env: test
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-test
  pubsubProjectId: entur-ror-test

  marduk:
    bucketName: marduk-test

  antu:
    bucketName: ror-antu-test

tiamatUrl: http://tiamat.tst.entur.internal

organisationRegistryUrl: https://api.staging.entur.io/organisations/v1/register/organisations

auth0:
  ror:
    url: https://ror-entur-staging.eu.auth0.com/
    audience: https://ror.api.staging.entur.io
  partner:
    tokenUri: https://partner.staging.entur.org/oauth/token
    clientId: N2f2Hinou2m6JiCRw4mYWUd89eBm0Jbp
    orgregister:
      audience: https://api.staging.entur.io

monitoringEnabled: true


ingress:
  domainName: .staging.entur.io