env: dev
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: ent-antu-dev

  marduk:
    bucketName: marduk-dev

  antu:
    bucketName: ror-antu-dev

tiamatUrl: http://tiamat.dev.entur.internal

organisationRegistryUrl: https://api.dev.entur.io/organisations/v1/register/organisations

auth0:
  ror:
    url: https://ror-entur-dev.eu.auth0.com/
    audience: https://ror.api.dev.entur.io
  partner:
    tokenUri: https://partner.dev.entur.org/oauth/token
    clientId: 373j34zZk6PHDf1Ap2LPbOBiL1f5LGte
    orgregister:
      audience: https://api.dev.entur.io

monitoringEnabled: true

ingress:
  domainName: .dev.entur.io