# Publish to the "AntuNetexValidationQueue" to start validation of NeTEx provided by EnturValidationDatasetFileHandle
# Assumes that the path set by EnturValidationDatasetFileHandle is valid in your local antu blobstore
POST http://localhost:8085/v1/projects/test/topics/AntuNetexValidationQueue:publish
Content-Type: application/json

{
  "messages": [
    {
      "attributes": {
        "EnturValidationClient": "Marduk",
        "EnturValidationCorrelationId": "14f2ba67-ce75-4be2-8052-6a0938069bc1",
        "EnturValidationDatasetFileHandle": "inbound/received/sjv/outbound_netex_rb_sjv-aggregated-netex.zip",
        "EnturValidationImportType": "ImportType_netex_flex",
        "EnturValidationProfile": "TimetableFlexibleTransport",
        "EnturValidationStage": "EnturValidationStageFlexPostValidation",
        "EnturDatasetReferential": "sjv"
      },
      "data": ""
    }
  ]
}
