validationRuleConfigs:
  # Entur custom rules
  - code: NSR_CODESPACE
    name: NSR_CODESPACE
    severity: ERROR
  - code: AUTHORITY_ID
    name: AUTHORITY_ID
    severity: ERROR
  - code: CODESPACE
    name: CODESPACE
    severity: ERROR
  - code: NETEX_ID_2
    name: NETEX_ID_2
    severity: ERROR
  - code: NETEX_ID_3
    name: NETEX_ID_3
    severity: ERROR
  - code: NETEX_ID_4
    name: NETEX_ID_4
    severity: ERROR
