validationRuleConfigs:
  # Entur custom rules
  - code: NSR_CODESPACE
    name: NSR Codespace not declared
    severity: ERROR
  - code: AUTHORITY_ID
    name: Authority invalid Id
    severity: ERROR
  - code: CODESPACE
    name: Codespace unknown
    severity: ERROR
  - code: NETEX_ID_2
    name: NeTEx ID invalid structure
    severity: ERROR
  - code: NETEX_ID_3
    name: NeTEx ID invalid element name inside structure
    severity: ERROR
  - code: NETEX_ID_4
    name: NeTEx ID with unapproved codespace
    severity: ERROR
  - code: NETEX_ID_4W
    name: NeTEx ID with unapproved codespace
    severity: WARNING
  - code: NETEX_FILE_NAME_1
    name: Invalid file name
    severity: ERROR
  - code: LINE_10
    name: Line not allowed in imported flexible line files
    severity: ERROR
  - code: SITE_FRAME_IN_COMMON_FILE_1
    name: stopPlaces not allowed in flexible line files
    severity: ERROR
  - code: INVALID_TRANSPORT_MODE
    name: Invalid transport mode
    severity: ERROR
  - code: TIMETABLED_PASSING_TIME_INCOMPLETE_TIME
    name: ServiceJourney has incomplete TimetabledPassingTime
    severity: ERROR
  - code: TIMETABLED_PASSING_TIME_INCONSISTENT_TIME
    name: ServiceJourney has inconsistent TimetabledPassingTime
    severity: ERROR
  - code: TIMETABLED_PASSING_TIME_NON_INCREASING_TIME
    name: ServiceJourney has non-increasing TimetabledPassingTime
    severity: ERROR
  - code: LOW_SPEED
    name: Slow travel in ServiceJourney
    severity: WARNING
  - code: HIGH_SPEED
    name: Too fast travel in ServiceJourney
    severity: ERROR
  - code: WARNING_SPEED
    name: Fast travel in ServiceJourney
    severity: WARNING
  - code: SAME_DEPARTURE_ARRIVAL_TIME
    name: Same departure/arrival time for consecutive stops
    severity: INFO
  - code: MISSING_SCHEDULED_STOP_ASSIGNMENT
    name: Missing ScheduledStopAssignment for StopPointInJourneyPattern
    severity: ERROR
  - code: JOURNEY_PATTERN_NO_BOARDING_ALLOWED_AT_LAST_STOP
    name: Last StopPointInJourneyPattern must not allow boarding
    severity: ERROR
  - code: JOURNEY_PATTERN_NO_ALIGHTING_ALLOWED_AT_FIRST_STOP
    name: First StopPointInJourneyPattern must not allow alighting
    severity: ERROR
  - code: DISTANCE_BETWEEN_STOP_POINT_AND_START_OF_LINE_STRING_EXCEEDS_MAX_LIMIT
    name: Distance between stop point and start of linestring, exceeds max limit, in LinkSequenceProjection
    severity: ERROR
  - code: DISTANCE_BETWEEN_STOP_POINT_AND_END_OF_LINE_STRING_EXCEEDS_MAX_LIMIT
    name: Distance between stop point and end of linestring, exceeds max limit, in LinkSequenceProjection
    severity: ERROR
  - code: DISTANCE_BETWEEN_STOP_POINT_AND_START_OF_LINE_STRING_EXCEEDS_WARNING_LIMIT
    name: Distance between stop point and start of linestring, exceeds warning limit, in LinkSequenceProjection
    severity: WARNING
  - code: DISTANCE_BETWEEN_STOP_POINT_AND_END_OF_LINE_STRING_EXCEEDS_WARNING_LIMIT
    name: Distance between stop point and end of linestring, exceeds warning limit, in LinkSequenceProjection
    severity: WARNING
  - code: SAME_STOP_POINT_IN_JOURNEY_PATTERNS
    name: JourneyPatterns have same StopPoints
    severity: ERROR
