validationRuleConfigs:
  - code: TIMETABLED_PASSING_TIME_INCOMPLETE_TIME
    name: ServiceJourney has incomplete TimetabledPassingTime
    severity: WARNING
  - code: TIMETABLED_PASSING_TIME_INCONSISTENT_TIME
    name: ServiceJourney has inconsistent TimetabledPassingTime
    severity: WARNING
  - code: TIMETABLED_PASSING_TIME_NON_INCREASING_TIME
    name: ServiceJourney has non-increasing TimetabledPassingTime
    severity: WARNING
