apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: timetable-validation-v1-validation
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: timetable-validation-v1-validation-gcp2{{ .Values.ingress.domainName }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "antu.name" . }}
                port:
                  number: {{ .Values.service.http.externalPort }}
