gcp_project = "entur-dev-1287"
gcp_storage_project = "entur-ror-dev"
gcp_pubsub_project = "entur-ror-dev"
gcp_resources_project = "entur-ror-dev"
kube_namespace = "dev"
bucket_marduk_instance_name = "marduk-dev"
service_account_bucket_role = "roles/storage.admin"
