apiVersion: v1
data:
  application.properties: |+

    # Spring
    spring.main.sources=no.entur.antu
    spring.profiles.active=gcs-blobstore
    server.port={{ .Values.service.http.internalPort }}

    # Camel
    camel.springboot.name=antu
    camel.dataformat.json-jackson.module-refs=jacksonJavaTimeModule
    camel.cluster.kubernetes.enabled=true
    camel.cluster.kubernetes.cluster-labels[app]=antu
    camel.cluster.kubernetes.config-map-name=antu-leaders
    camel.servlet.mapping.context-path=/services/*
    # the Camel shutdown timeout must be shorter than the Kubernetes terminationGracePeriod
    antu.shutdown.timeout=25
    antu.camel.redelivery.max=0

    # Organisation register
    antu.organisation.registry.url={{ .Values.organisationRegistryUrl }}

    # Stop place register
    antu.stop.registry.id.url=http://tiamat/services/stop_places
    antu.stop.refresh.interval=fireNow=true&startDelayedSeconds=10&stateful=true&trigger.repeatInterval=30000&trigger.repeatCount=3


    # Validators
    antu.schema.validation.enabled=true

    # PubSub
    antu.pubsub.project.id={{ .Values.gcp.pubsubProjectId }}
    spring.cloud.gcp.project-id=${antu.pubsub.project.id}
    camel.component.google-pubsub.service-account-key=file:/etc/antu-service-account/credentials.json

    #OAuth2 Resource Server
    spring.security.oauth2.resourceserver.jwt.issuer-uri={{ .Values.auth0.ror.url }}
    antu.oauth2.resourceserver.auth0.ror.jwt.audience={{ .Values.auth0.ror.audience }}
    antu.oauth2.resourceserver.auth0.ror.claim.namespace=https://ror.entur.io/

    # Blobstore
    blobstore.gcs.project.id={{ .Values.gcp.blobstoreProjectId }}
    blobstore.gcs.credential.path=/etc/antu-service-account/credentials.json
    blobstore.gcs.marduk.container.name={{ .Values.gcp.marduk.bucketName }}
    blobstore.gcs.antu.container.name={{ .Values.gcp.antu.bucketName }}

    # Redis
    spring.redis.host=${REDIS_HOST}
    spring.redis.port=6379

    # Actuator
    management.endpoints.enabled-by-default=false
    management.endpoint.health.enabled=true
    management.health.defaults.enabled=false
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=health,prometheus
    management.endpoints.jmx.exposure.exclude=*


    # Logging
    logging.config=classpath:logback.xml
    logging.level.no.entur=INFO
    logging.level.no.entur.antu=INFO
    logging.level.org.apache=INFO
    logging.level.org.apache.camel.component.http.HttpComponent=WARN


kind: ConfigMap
metadata:
  name: {{ template "antu.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
