apiVersion: v1
data:
  application.properties: |+

    # Spring
    spring.main.sources=no.entur.antu
    spring.profiles.active=gcs-blobstore
    server.port={{ .Values.service.http.internalPort }}
    spring.quartz.auto-startup=false

    # Camel
    camel.springboot.name=antu
    camel.dataformat.jackson.module-refs=jacksonJavaTimeModule
    camel.dataformat.jackson.include=NON_NULL
    camel.cluster.kubernetes.enabled=true
    camel.cluster.kubernetes.cluster-labels[app]=antu
    camel.cluster.kubernetes.config-map-name=antu-leaders
    camel.servlet.mapping.context-path=/services/*
    camel.springboot.streamCachingEnabled=false
    camel.springboot.streamCachingSpoolEnabled=true
    # the Camel shutdown timeout must be shorter than the Kubernetes terminationGracePeriod
    antu.shutdown.timeout=75
    antu.camel.redelivery.max=0

    # Organisation register
    antu.organisation.registry.url={{ .Values.organisationRegistryUrl }}
    antu.organisation.refresh.interval=trigger.repeatInterval=1800000&trigger.repeatCount=-1&stateful=true

    # Stop place register
    antu.stop.registry.id.url={{ .Values.tiamatUrl }}/services/stop_places
    # Refresh stop place cache at 01:00 and 14:00 every day
    antu.stop.refresh.interval=?cron=0+0+24,14+?+*+*
    stopplace.registry.url={{ .Values.stopplaceRegistryUrl }}


    # Validators
    antu.netex.validation.schema.skip=false

    # Kubernetes
    antu.kubernetes.namespace={{ .Values.kubernetes.namespace }}
    antu.kubernetes.maxpods={{ .Values.kubernetes.maxPods }}

    # PubSub
    antu.pubsub.project.id={{ .Values.gcp.pubsubProjectId }}
    spring.cloud.gcp.project-id=${antu.pubsub.project.id}

    camel.component.google-pubsub.synchronous-pull-retryable-codes=DEADLINE_EXCEEDED

    #OAuth2 Resource Server
    antu.oauth2.resourceserver.auth0.ror.claim.namespace=https://ror.entur.io/

    # OAuth2 Resource Server for Entur Partner tenant
    antu.oauth2.resourceserver.auth0.entur.partner.jwt.issuer-uri={{ .Values.auth0.partner.url }}
    antu.oauth2.resourceserver.auth0.entur.partner.jwt.audience={{ .Values.auth0.ror.audience }}

    # OAuth2 Resource Server for RoR tenant
    antu.oauth2.resourceserver.auth0.ror.jwt.issuer-uri={{ .Values.auth0.ror.url }}
    antu.oauth2.resourceserver.auth0.ror.jwt.audience={{ .Values.auth0.ror.audience }}

    #Oauth2 Client
    spring.security.oauth2.client.provider.orgregister.token-uri={{ .Values.auth0.client.tokenUri }}
    spring.security.oauth2.client.registration.orgregister.client-id={{ .Values.auth0.client.clientId }}
    spring.security.oauth2.client.registration.orgregister.authorization-grant-type=client_credentials
    orgregister.oauth2.client.audience={{ .Values.auth0.client.orgregister.audience }}

    # Authorization
    antu.security.authorization-service=token-based

    # Blobstore
    blobstore.gcs.project.id={{ .Values.gcp.blobstoreProjectId }}
    blobstore.gcs.marduk.container.name={{ .Values.gcp.marduk.bucketName }}
    blobstore.gcs.antu.exchange.container.name={{ .Values.gcp.antu.exchangeBucketName }}
    blobstore.gcs.antu.container.name={{ .Values.gcp.antu.bucketName }}
    antu.netex.stop.current.filename=tiamat/CurrentAndFuture_latest.zip

    # Redis
    spring.data.redis.host=${REDIS_HOST}
    spring.data.redis.port=${REDIS_PORT}
    antu.redis.server.trust.store.file=/deployments/truststore/redis-server-ca.jks

    # Actuator
    management.endpoints.enabled-by-default=false
    management.endpoint.health.enabled=true
    management.health.defaults.enabled=false
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=health,prometheus
    management.endpoints.jmx.exposure.exclude=*


    # Logging
    logging.config=classpath:logback.xml
    logging.level.no.entur=INFO
    logging.level.no.entur.antu=INFO
    logging.level.org.apache=INFO
    logging.level.org.apache.camel.component.http.HttpComponent=WARN

kind: ConfigMap
metadata:
  name: {{ template "antu.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
