apiVersion: v1
kind: ServiceAccount
metadata:
  name: antu-service-account
  labels:
  {{- include "common.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: antu-service-account
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: antu-service-account
subjects:
  - kind: ServiceAccount
    name: antu-service-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: antu-service-account
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "endpoints", "configmaps"]
    verbs: ["get", "watch", "list"]

