env: dev
replicas: 1

gcp:
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: entur-ror-dev

  marduk:
    bucketName: marduk-dev

  antu:
    bucketName: ror-antu-dev

organisationRegistryUrl: https://api.dev.entur.io/organisations/v1/register/organisations

auth0:
  ror:
    url: https://ror-entur-dev.eu.auth0.com/
    audience: https://ror.api.dev.entur.io

oauth2:
  client:
    id: QJwqqzV5o19bcumOUEJDxcOh6r34wu5R
    url: https://ror-entur-dev.eu.auth0.com/oauth/token
    audience: https://ror.api.dev.entur.io

monitoringEnabled: true

ingress:
  loadBalancerIP: 35.205.170.68