env: staging
replicas: 1

gcp:
  blobstoreProjectId: entur-ror-test
  pubsubProjectId: entur-ror-test

  marduk:
    bucketName: marduk-test

organisationRegistryUrl: https://api.staging.entur.io/organisations/v1/register/organisations/

monitoringEnabled: true

ingress:
  loadBalancerIP: 130.211.80.129