image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: "2"
  memLimit: 4000Mi
  cpuRequest: "1"
  memRequest: 4000Mi
  xmx: 3000m

horizontalPodAutoscaler:
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 50

kubernetes:
  namespace: antu
  maxPods: 10

secrets:
  partner-auth0-secret:
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ORGREGISTER_CLIENT_SECRET