image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  memLimit: 3000Mi
  cpuRequest: 1500m
  memRequest: 3000Mi
  xmx: 2500m

horizontalPodAutoscaler:
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 50

kubernetes:
  namespace: antu
  maxPods: 10
secrets:
  antu-auth-secret:
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ORGREGISTER_CLIENT_SECRET