image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: 1000m
  memLimit: 1800Mi
  cpuRequest: 1000m
  memRequest: 1300Mi
  xmx: 1000m

horizontalPodAutoscaler:
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 50
