name: Build and push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  maven-verify:
    env:
      JFROG_USER: ${{ secrets.ARTIFACTORY_AUTH_USER }}
      JFROG_PASS: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - name: Run maven build
        run: mvn verify -PprettierCheck -Dprettier.nodePath=node -Dprettier.npmPath=npm
      - uses: actions/upload-artifact@v4.6.2
        with:
          path: target/*-SNAPSHOT.jar
      - name: Sonar Scan
        if: github.repository_owner == 'entur' && github.ref == 'refs/heads/main'
        env:
          SONAR_TOKEN: ${{ secrets.ENTUR_SONAR_PASSWORD }}
          SONAR_PROJECT_NAME: ${{ github.event.repository.name }}
          SONAR_PROJECT_KEY: entur_${{ github.event.repository.name }}
        run: |
          mvn     org.jacoco:jacoco-maven-plugin:prepare-agent verify \
                  org.jacoco:jacoco-maven-plugin:report sonar:sonar \
                  -P prettierSkip \
                  -Dmaven.main.skip \
                  -DskipTests \
                  -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                  -Dsonar.organization=enturas-github \
                  -Dsonar.projectName=${SONAR_PROJECT_NAME} \
                  -Dsonar.host.url=https://sonarcloud.io \
                  -Dsonar.token=${SONAR_TOKEN}

  docker-build:
    if: github.repository_owner == 'entur' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [maven-verify]
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: artifact
      build_artifact_path: target
  docker-push:
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1